version: 2
registries:
  cloudsmith-cargo-basic:
    type: git
    url: https://dl.cloudsmith.io/basic/cloudsmith/testing-private/cargo/index.git
    username: ciara-carey
    password: ${{secrets.CS_PASSWORD}}
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    registries:
      - cloudsmith-cargo-basic
    schedule:
      interval: "daily"
      time: "10:45"
